const UNSPLASH_API_KEY = process.env.UNSPLASH_API_KEY;
// const YOUTUBE_API_KEY = "AIzaSyDCh4pDvYFVJe5Lu_DbHT_kBgrJma83FxI";
// const YOUTUBE_API_KEY = "AIzaSyCjjqjn7wqsKm5EcKn-n3gMJgcl3-iOlpc";
const YOUTUBE_API_KEY = process.env.YOUTUBE_API_KEY;
// const OPEN_AI_KEY = "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";
const OPEN_AI_KEY = process.env.OPEN_AI_KEY;
exports.UNSPLASH_API_KEY = UNSPLASH_API_KEY;
exports.YOUTUBE_API_KEY = YOUTUBE_API_KEY;
exports.OPEN_AI_KEY = OPEN_AI_KEY;
